// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.9.1

import { Writer, Reader } from "as-proto/assembly";

export class Amount {
  static encode(message: Amount, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.amount);
  }

  static decode(reader: Reader, length: i32): Amount {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Amount();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.amount = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  amount: u64;

  constructor(amount: u64 = 0) {
    this.amount = amount;
  }
}
